#!/bin/sh
#
# A quick way to clean up the new files every time one runs git add

# Get the list of staged files
staged_files=$(git diff --cached --name-only --diff-filter=ACMR)

# npx markdown-notes-tree --subdirectoryDescriptionOnNewLine --notesBeforeDirectories --silent
# git add ./README.md

# Loop through the list of staged files
for file in $staged_files; do
    # Cleanup each file
    if [[ ! $string == *"README"* ]]; then
        ./.git/hooks/clean.py $file

        # Add the updated version to the commit
        git add $file
    fi
done
